#!/bin/bash 
# shellcheck source=/dev/null
. /init_functions

assert_ok mount_setup               
assert_ok nvidia_get_devices        
# If the GPU is not supported do not do any GPU handling
#assert_ok nvidia_check_if_supported 
if assert_ok nvidia_check_if_supported; then 
        # Only if we're cold-plugging we would detect GPUs in this phase, 
        # skip any GPU related setup if we don't have any GPUs
        if [ -n "${gpu_device_ids}" ]; then
                assert_ok nvidia_reset_gpus
                assert_ok nvidia_persistenced
                assert_ok nvidia_container_toolkit
        fi
fi 
assert_ok nvidia_process_kernel_params 
# Setting AGENT_INIT to yes will make the agent the init process
exec /sbin/init
