name: CI | Basic amd64 tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

  workflow_call:
    inputs:
      tarball-suffix:
        required: false
        type: string
      commit-hash:
        required: false
        type: string
      target-branch:
        required: false
        type: string
        default: ""

jobs:
  run-vfio:
    strategy:
      fail-fast: false
      matrix:
        vmm: ['clh', 'qemu']
    runs-on: nvidia-gpu-ubuntu-2204
    env:
      GOPATH: ${{ github.workspace }}
      KATA_HYPERVISOR: ${{ matrix.vmm }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit-hash }}
          fetch-depth: 0

      - name: Rebase atop of the latest target branch
        run: |
          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
        env:
          TARGET_BRANCH: ${{ inputs.target-branch }}

      - name: Install dependencies
        run: bash tests/functional/vfio/gha-run.sh install-dependencies

#      - name: get-kata-tarball
#        uses: actions/download-artifact@v3
#        with:
#          name: kata-static-tarball-amd64${{ inputs.tarball-suffix }}
#          path: kata-artifacts

      - name: Run vfio tests
        timeout-minutes: 15
        run: bash tests/functional/vfio/gha-run.sh run
