name: Kata Containers Nightly CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  kata-containers-ci-on-push:
    uses: ./.github/workflows/ci.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: "nightly"
      tag: ${{ github.sha }}-nightly
      target-branch: ${{ github.ref_name }}
    secrets: inherit
