name: Release Kata Containers
on:
  workflow_dispatch

permissions:
  contents: read

jobs:

  build-and-push-helm-chart:
    runs-on: ubuntu-22.04
#    needs: release
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Symlink helm-chart to charts for easier consumption
        run: |
          ln -s tools/packaging/kata-deploy/helm-chart charts
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
